# Generated by Django 5.1.1 on 2024-09-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
